# Generated by Django 6.0.3 on 2026-03-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('canceled', 'Скасовано')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.schedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.masterservice')),
            ],
        ),
    ]
