# Generated by Django 6.0.3 on 2026-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_booking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Irenka Nails', max_length=100)),
                ('bg_color', models.CharField(default='#E6E6FA', max_length=7)),
                ('container_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('hero_title', models.CharField(default='Твій ідеальний манікюр', max_length=300)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('emblem', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
    ]
