# Generated by Django 6.0.3 on 2026-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Якість', max_length=100)),
                ('description', models.TextField(default='Працюємо на найкращих та перевірених матеріалах', max_length=500)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
    ]
