# Generated by Django 6.0.3 on 2026-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_advantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(default='Якість', max_length=100, unique=True),
        ),
    ]
