# Generated by Django 6.0.3 on 2026-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_advantage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=100)),
                ('contact', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
    ]
