# Generated by Django 6.0.3 on 2026-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_contactdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
