# Generated by Django 6.0.3 on 2026-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contactdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
