# Generated by Django 6.0.3 on 2026-04-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_contactdetail_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
