# Generated by Django 6.0.3 on 2026-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
