# Generated by Django 6.0.3 on 2026-04-24 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_gallery_date_alter_gallery_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Переваги', 'verbose_name_plural': 'Переваги'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнти', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='contactdetail',
            options={'verbose_name': 'Контактна інформація', 'verbose_name_plural': 'Контактна інформація'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Майстри', 'verbose_name_plural': 'Майстри'},
        ),
        migrations.AlterModelOptions(
            name='masterservice',
            options={'verbose_name': 'Майстер-послуги', 'verbose_name_plural': 'Майстер-послуги'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Розклад', 'verbose_name_plural': 'Розклад'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуги', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування сайту', 'verbose_name_plural': 'Налаштування сайту'},
        ),
        migrations.AlterField(
            model_name='advantage',
            name='description',
            field=models.TextField(default='Працюємо на найкращих та перевірених матеріалах', max_length=500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Місце'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='title',
            field=models.CharField(default='Якість', max_length=100, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.schedule', verbose_name='Розклад'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.masterservice', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікується'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Загальна ціна'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я та призвище"),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='badge',
            field=models.CharField(max_length=100, verbose_name='Значок'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контакт(посилання)'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Місце'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва(опис)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я майстра"),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.master', verbose_name='Майстер'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нова ціна'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.master', verbose_name='Майстер'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва послуги'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bg_color',
            field=models.CharField(default='#E6E6FA', max_length=7, verbose_name='Основний колір'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='container_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Колір контейнера'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Емблема'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='Підзаголовок сайту'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Твій ідеальний манікюр', max_length=300, verbose_name='Гасло сайту'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Irenka Nails', max_length=100, verbose_name='Назва сайту'),
        ),
    ]
